a = int(input("Enter a? "))
b = int(input("Enter b? "))
c = int(input("Enter c? "))
if a < b and a < c: print("a is Smallest")
if b < a and b < c: print("b is Smallest")
if c < a and c < b: print("c is Smallest")